name: python_CI

on: workflow_call

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-pip-${{ hashFiles('test/requirements.txt') }}
        restore-keys: ${{ env.pythonLocation }}-pip 
    - name: Check for existence of .github/install.sh
      id: check_install
      uses: andstor/file-existence-action@v1
      with:
        files: ".github/install.sh"
    - name: Run .github/install.sh if it exists
      if: steps.check_install.outputs.files_exists == 'true'
      run: |
        ./.github/install.sh
    - name: install ci packages
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install flake8 flake8-bandit pylint pylint-mccabe pytest pytest-benchmark pytest-sugar
    - name: install testing requirements
      run: |
        pip install -r test/requirements.txt
    - name: install project packages 
      run: |
        pip install -r requirements.txt
      if: always()
    - name: Check for existence of setup.py
      id: check_setup
      uses: andstor/file-existence-action@v1
      with:
        files: "setup.py"  
    - name: Run setup.py to install as a package if it exists
      if: steps.check_setup.outputs.files_exists == 'true'
      run: |
        python setup.py install
    - name: flake8-bandit
      run: flake8 . --exit-zero --max-complexity=10 --max-line-length=127
      if: always()
    - name: Analysing the code with pylint
      run: |
        echo $(git ls-files '*.py')
        pylint $(git ls-files '*.py') --fail-under=9
      if: always()
    - name: run tests
      run: |
        pytest --rootdir=. --color=yes
      if: always()
    - name: Check for existence of ./github/resource
      id: check_resource
      uses: andstor/file-existence-action@v1
      with:
        paths: ".github/resource.txt"
    - name: Set resource variable (if it exists)
      if: steps.check_resource.outputs.files_exists == 'true'
      run: |
        res=$(cat resource)
        echo "RESOURCE=$RES" >> $GITHUB_ENV
    - name: upload resource (if it exists)
      if: steps.check_resource.outputs.files_exists == 'true'
      uses: actions/upload-artifact@v2
      with:
          name: resource
          path: ${{ github.workspace }}${{ env.RESOURCE }}
